# Generated by Django 3.1.3 on 2020-11-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage_routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivos',
            options={'verbose_name': 'Archivo'},
        ),
        migrations.AddField(
            model_name='archivos',
            name='description',
            field=models.CharField(default='Archivos de rutas', max_length=50, verbose_name='Descripción de archivos'),
            preserve_default=False,
        ),
    ]
