# Generated by Django 3.1.3 on 2020-11-06 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_routes', '0002_auto_20201106_0054'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage_routes', '0002_auto_20201105_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Indique el nombre del cliente inscrito en este portal', max_length=100, verbose_name='Nombre del cliente')),
                ('direccion', models.CharField(blank=True, help_text='Especifique la dirección donde el cliente se encuentra ubicado', max_length=200, verbose_name='Dirección del cliente')),
                ('ciudad', models.ForeignKey(help_text='Indique la ciudad del cliente', on_delete=django.db.models.deletion.CASCADE, to='login_routes.ciudad', verbose_name='Ciudad del cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField(default=5000, help_text='Estipule la maxima capacidad de carga en kilogramos para este vehiculo', verbose_name='Capacidad de carga (en kg)')),
                ('conductor', models.OneToOneField(help_text='Indique el conductor asignado para este vehículo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Conductor del vehículo')),
            ],
            options={
                'verbose_name': 'Vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_dummies', models.IntegerField(default=0, help_text='Indique la cantidad de dummies para este pedido', null=True, verbose_name='Cantidad de dommies')),
                ('cantidad_giftcards', models.IntegerField(default=0, help_text='Indique la cantidad de gift cards para este pedido', null=True, verbose_name='Cantidad de gift cards')),
                ('cantidad_handsets', models.IntegerField(default=0, help_text='Indique la cantidad de handsets cards para este pedido', null=True, verbose_name='Cantidad de handset')),
                ('cantidad_modems', models.IntegerField(default=0, help_text='Indique la cantidad de modems para este pedido', null=True, verbose_name='Cantidad de modems')),
                ('cantidad_packs', models.IntegerField(default=0, help_text='Indique la cantidad de packs para este pedido', null=True, verbose_name='Cantidad de packs')),
                ('cantidad_prepaid', models.IntegerField(default=0, help_text='Indique la cantidad de prepaid cards para este pedido', null=True, verbose_name='Cantidad de prepaid cards')),
                ('cantidad_simcards', models.IntegerField(default=0, help_text='Indique la cantidad de sim cards para este pedido', null=True, verbose_name='Cantidad de sim cards')),
                ('cantidad_simcards_prep', models.IntegerField(default=0, help_text='Indique la cantidad de sim cards prepagas para este pedido', null=True, verbose_name='Cantidad de sim cards prepagas')),
                ('cantidad_supplies', models.IntegerField(default=0, help_text='Indique la cantidad de embalajes de productos para este pedido', null=True, verbose_name='Cantidad de embalajes')),
                ('cliente', models.ForeignKey(help_text='Indique quien es el cliente propietario de este pedido', on_delete=django.db.models.deletion.CASCADE, to='mainpage_routes.cliente', verbose_name='Cliente dueño del pedido')),
            ],
            options={
                'verbose_name': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_min', models.IntegerField(default=0, help_text='Es decir, vehículo llega a la dirección, se estaciona, entonces es el tiempo que se demora el conductor o el ayudante en buscar el pedido en el vehículo y entregárselo al cliente', verbose_name='Tiempo de servicio')),
                ('ai_min', models.IntegerField(default=0, help_text='Es decir, el vehículo puede llegar  después del minuto x a entregar el pedido, en ese caso particular fueron tomadas según la normativa y restricciones según las zonas de la ciudad para el movimiento de los vehículos de carga, siendo las horas valle', verbose_name='Ventana de inicio')),
                ('bi_min', models.IntegerField(default=0, help_text='Es decir, es el tiempo máximo en el que puede llegar el vehículo para entregar el pedido', verbose_name='Ventana de fin')),
                ('pedido', models.ForeignKey(help_text='Asigne el pedido que será despachado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage_routes.pedido', verbose_name='Pedido a despachar')),
            ],
            options={
                'verbose_name': 'Despacho',
            },
        ),
    ]
