# Generated by Django 3.1.3 on 2020-11-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage_routes', '0004_auto_20201106_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(default='ABC123', help_text='Ingrese la placa del vehículo a registrar para su identificación correcta', max_length=6, verbose_name='Placa del vehículo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cantidad_dummies',
            field=models.IntegerField(default=0, help_text='Indique la cantidad de dummies para este pedido', null=True, verbose_name='Cantidad de dummies'),
        ),
    ]
