# Generated by Django 3.1.3 on 2020-11-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage_routes', '0005_auto_20201106_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(help_text='Ingrese la placa del vehículo a registrar para su identificación correcta', max_length=6, unique=True, verbose_name='Placa del vehículo'),
        ),
    ]
