# Generated by Django 3.1.3 on 2020-11-07 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_routes', '0002_auto_20201106_0054'),
        ('mainpage_routes', '0006_auto_20201106_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='ciudad',
            field=models.ForeignKey(help_text='Indique en que ciudad se encuentra situado el vehículo a usar en el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_routes.ciudad', verbose_name='Ciudad donde se ubica'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='direccion',
            field=models.CharField(blank=True, help_text='Especifique la dirección donde el vehículo se encuentra ubicado', max_length=200, verbose_name='Dirección de la ubicación del vehículo'),
        ),
    ]
