# Generated by Django 3.1.3 on 2020-11-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage_routes', '0008_auto_20201106_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='direccion',
            field=models.CharField(default='Calle 22 # 56-24', help_text='Especifique la dirección donde el vehículo se encuentra ubicado', max_length=200, verbose_name='Dirección de la ubicación del vehículo'),
        ),
    ]
