# Generated by Django 3.1.3 on 2020-11-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage_routes', '0009_auto_20201106_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despacho',
            options={'get_latest_by': 'id', 'verbose_name': 'Despacho'},
        ),
        migrations.AlterField(
            model_name='archivos',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Descripción de archivos'),
        ),
    ]
