# Generated by Django 3.1.3 on 2020-11-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage_routes', '0010_auto_20201107_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Descripción de archivos'),
        ),
    ]
