# Generated by Django 3.1.3 on 2020-11-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Indique el nombre de la ciudad a registrar', max_length=50, verbose_name='Nombre de la ciudad')),
            ],
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Conductor'},
        ),
    ]
