# Generated by Django 3.1.3 on 2020-11-07 16:39

from django.db import migrations, models
import login_routes.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_routes', '0003_auto_20201107_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cedula',
            field=models.CharField(default='8016139348', help_text='Indique su número de cédula o licencia de conducir para su identificación en el sistema', max_length=10, unique=True, validators=[login_routes.models.only_digits], verbose_name='Número de cédula'),
        ),
        migrations.AlterField(
            model_name='users',
            name='licencia',
            field=models.CharField(default='906158181000324', help_text='Indique su número de licencia de conducir para su identificación en el sistema', max_length=15, unique=True, validators=[login_routes.models.only_digits], verbose_name='Número de licencia de conducción'),
        ),
    ]
